/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.31).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package net.petstore.consumer;


import net.petstore.model.Order;

public interface StoreApi {


   void deleteOrder(Long orderId);

   void placeOrder(Order body);

}
